[package]
name = "extfmt"
version = "0.2.0"
authors = ["Gilad Naaman <gilad@naaman.io>"]
description="Extended formatting options for commmon types"
edition = "2021"

license="Apache-2.0"
repository="https://github.com/Gilnaa/extfmt"
readme="README.md"

keywords=["formatting"]
categories=["value-formatting"]

[dependencies]
